import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {buildTokens,palette} from '../src/tokens.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const write=(p,c)=>{const dest=path.join(root,p);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,c);};
const art='data:image/png;base64,'+fs.readFileSync(path.join(root,'assets/nezuko-moonlight.png')).toString('base64');
const tokens=read('src/tokens.mjs').replace(/export /g,'');
const fontCSS=['Sans','Serif'].map(f=>`@font-face{font-family:"Moonlight ${f}";src:url("data:font/woff;base64,${fs.readFileSync(path.join(root,`assets/Moonlight${f}-Subset.woff`)).toString('base64')}") format("woff");font-weight:400;font-style:normal;font-display:swap}`).join('\n');
const css=fontCSS+'\n'+read('src/native.css');
const client=read('src/client.mjs').replace(/^import .*;\n/,'').replace(/export /g,'').replace("'__ART_DATA_URI__'",()=>JSON.stringify(art)).replace("'__NATIVE_CSS__'",()=>JSON.stringify(css));
write('lib/client.js',`// Generated by scripts/build.mjs; edit src files and rebuild.\nwindow.__ModuleLoader__.load({id:'dsh-theme-nezuko',factory:(require)=>{\n${tokens}\n${client}\nreturn {inject,apply};\n}});\n`);
write('lib/index.js',read('src/index.mjs'));
const previewCSS=fontCSS+'\n'+read('preview/preview.css')+`\n:root{--ui:"Moonlight Sans",-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;--serif:"Moonlight Serif","Noto Serif CJK SC","Songti SC",SimSun,serif}\n.sidebar{position:relative}.sidebar-pattern{position:absolute;inset:0;width:100%;height:100%;color:var(--pink);opacity:.026;pointer-events:none;z-index:-1}\n`;
const previewJS=read('preview/preview.js').replace('__PREVIEW_ART_BASE64__',()=>art.slice(art.indexOf(',')+1));
const html=read('preview/index.template.html').replace('/*__PREVIEW_CSS__*/',()=>previewCSS).replace('/*__PREVIEW_JS__*/',()=>previewJS);
write('Nezuko-Preview.html',html);
write('theme.tokens.json',JSON.stringify({name:'祢豆子 · 月下守护',id:'dsh-theme-nezuko',version:JSON.parse(read('package.json')).version,palette,tokens:buildTokens()},null,2)+'\n');
// CSS fallback: import into an existing custom-CSS facility on the DSH origin.
// This adds palette + a small geometric pattern; the full illustration is
// provided by the native plugin (large CSS URL tokens hit browser size limits).
const block=mode=>Object.entries(buildTokens()).map(([n,v])=>`  ${n}: ${v[mode]} !important;`).join('\n');
const pattern='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="80" height="139" viewBox="0 0 80 138.56"><path d="M40 0 0 69.28 40 138.56 80 69.28ZM0 0 80 138.56M80 0 0 138.56M0 69.28H80M40 0V138.56M0 69.28 40 46.19 80 69.28 40 92.37Z" fill="none" stroke="#b87b96" stroke-width=".7" opacity=".07"/></svg>');
write('Nezuko-Standalone.css',`/* 祢豆子 · 月下守护 | DSH palette + asanoha-pattern CSS fallback. Full character artwork is in the native plugin. Remove this stylesheet to undo. */\n${fontCSS}\nbody {\n${block('light')}\n}\nbody[data-ds-dark-theme] {\n${block('dark')}\n}\nbody [data-phase]:has([data-conversation-scroll]){background-image:url("${pattern}");background-repeat:repeat;background-size:80px 139px}\n`);
for(const p of ['lib/client.js','Nezuko-Preview.html','Nezuko-Standalone.css'])console.log(`${p}: ${(fs.statSync(path.join(root,p)).size/1024/1024).toFixed(2)} MiB`);
