import {createRequire} from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const browser=await chromium.launch({headless:true,...(process.env.NEZUKO_QA_BROWSER?{executablePath:process.env.NEZUKO_QA_BROWSER}:{}),args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1536,height:960},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const requests=[];page.on('request',r=>requests.push(r.url()));
await page.goto('file://'+path.join(root,'Nezuko-Preview.html'));
await page.evaluate(()=>document.fonts.ready);
const artwork=await page.evaluate(async()=>{const bg=getComputedStyle(document.querySelector('.scene')).backgroundImage;const url=bg.match(/^url\(["']?(.*?)["']?\)$/)?.[1];if(!url)return null;const img=new Image();img.src=url;await img.decode();return {width:img.naturalWidth,height:img.naturalHeight};});
assert.ok(artwork&&artwork.width>1000,'Embedded artwork must decode and be applied as the scene background');
await page.screenshot({animations:"disabled",path:path.join(root,'qa/Nezuko-Desktop.png'),fullPage:true});
assert.equal(await page.locator('#view-home').isVisible(),true);
await page.locator('.top-actions [data-action="mode"]').click();
assert.equal(await page.locator('html').getAttribute('data-mode'),'light');
await page.screenshot({animations:"disabled",path:path.join(root,'qa/Nezuko-Daylight.png'),fullPage:true});
await page.locator('.top-actions [data-action="settings"]').click();
assert.equal(await page.locator('#settings-drawer').isVisible(),true);
await page.locator('[data-mode-choice="dark"]').click();
await page.locator('#art-strength').fill('60');
await page.locator('#art-strength').dispatchEvent('input');
assert.equal(await page.locator('#art-output').textContent(),'60%');
await page.locator('#settings-drawer [data-action="focus"]').click();
assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('focus-mode')),true);
await page.locator('#settings-drawer [data-action="focus"]').click();
await page.locator('[data-action="reset"]').click();
await page.screenshot({animations:"disabled",path:path.join(root,'qa/Nezuko-Settings.png'),fullPage:true});
await page.keyboard.press('Escape');
assert.equal(await page.locator('#settings-drawer').isVisible(),false);
await page.reload();await page.evaluate(()=>document.fonts.ready);
assert.equal(await page.locator('html').getAttribute('data-mode'),'dark');
await page.locator('[data-prompt]').first().click();
assert.ok((await page.locator('#prompt').inputValue()).length>0);
await page.locator('#prompt').fill('<img src=x onerror=alert(1)> 测试灵感');
await page.locator('#home-form .send-button').click();
assert.equal(await page.locator('#view-chat').isVisible(),true);
assert.equal(await page.locator('.user-bubble img').count(),0);
assert.ok((await page.locator('#messages').textContent()).includes('没有发送给任何模型'));
await page.locator('.session-row[data-action="sample"]').click();
await page.screenshot({animations:"disabled",path:path.join(root,'qa/Nezuko-Conversation.png'),fullPage:true});
await page.keyboard.press('Control+k');
await page.locator('#command-input').fill('代码');
await page.keyboard.press('Enter');
assert.equal(await page.locator('#view-code').isVisible(),true);
await page.screenshot({animations:"disabled",path:path.join(root,'qa/Nezuko-Code.png'),fullPage:true});
await page.keyboard.press('Control+k');
await page.locator('#command-input').fill('不存在的快捷操作');
assert.equal(await page.locator('.command-empty').isVisible(),true);
await page.keyboard.press('Escape');
await page.locator('.rail-button[data-view="guide"]').click();
assert.equal(await page.locator('#view-guide').isVisible(),true);
await page.locator('.brand-mark').click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({animations:"disabled",path:path.join(root,'qa/Nezuko-Mobile.png'),fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('.mobile-menu').click();
assert.equal(await page.locator('.sidebar.sidebar-open').isVisible(),true);
await page.locator('.sidebar .new-chat').click();
assert.equal(await page.locator('.sidebar.sidebar-open').count(),0);
await page.emulateMedia({reducedMotion:'reduce'});
assert.equal(await page.locator('#petals').evaluate(e=>getComputedStyle(e).display),'none');
await page.setViewportSize({width:1536,height:960});
await page.emulateMedia({reducedMotion:'no-preference'});
const tokenData=JSON.parse(fs.readFileSync(path.join(root,'theme.tokens.json'),'utf8'));
const colorLuminance=hex=>{const v=hex.slice(1).match(/../g).map(s=>parseInt(s,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return .2126*v[0]+.7152*v[1]+.0722*v[2];};
const contrast=(a,b)=>{const x=colorLuminance(a),y=colorLuminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);};
const contrastReport={};
for(const mode of ['light','dark']){const p=tokenData.palette[mode];contrastReport[mode]={};for(const role of ['base','side','surface','raised','overlay']){const score=contrast(p.text,p[role]);contrastReport[mode][`text/${role}`]=Number(score.toFixed(2));assert.ok(score>=7,`${mode} text ${role}: ${score}`);}for(const role of ['accent','green','gold','secondary','tertiary']){const score=contrast(p[role],p.base);contrastReport[mode][`${role}/base`]=Number(score.toFixed(2));assert.ok(score>=4.5,`${mode} ${role}: ${score}`);}}
// Validate native plugin lifecycle with a host-contract fixture. This is not a live DSH test.
await page.goto('file://'+path.join(root,'qa/fixture.html'));
await page.evaluate(()=>{
  window.__ModuleLoader__={load:m=>{window.nativePlugin=m.factory(()=>{throw new Error('Unexpected dependency');});}};
  const overrides=new Map(), listeners=new Set();let seq=0;
  window.testHost={preference:'dark',overrides,listeners,disposers:[],ctx:{
    effect(fn){window.testHost.disposers.push(fn());},
    on(event,fn){listeners.add(fn);return()=>listeners.delete(fn);},
    theme:{getTheme(){return{active:{colorScheme:window.testHost.preference},preference:window.testHost.preference};},setTheme(s){window.testHost.preference=s;listeners.forEach(fn=>fn());},overrideTokens(id,t){for(const value of Object.values(t))if(typeof value.light!=='string'||typeof value.dark!=='string')throw new Error('Invalid token pair');const entry={seq:seq++,t};overrides.set(id,entry);listeners.forEach(fn=>fn());return()=>{if(overrides.get(id)===entry){overrides.delete(id);listeners.forEach(fn=>fn());}};}}
  }};
});
await page.addScriptTag({path:path.join(root,'lib/client.js')});
await page.evaluate(()=>window.nativePlugin.apply(window.testHost.ctx));
assert.equal(await page.locator('.nz-launcher').count(),1);
assert.equal(await page.evaluate(()=>window.testHost.overrides.size),1);
await page.locator('.nz-launcher').click();
await page.locator('[data-nz-mode="light"]').click();
assert.equal(await page.evaluate(()=>window.testHost.preference),'light');
await page.locator('[data-nz-setting="art"]').fill('50');
await page.locator('[data-nz-setting="art"]').dispatchEvent('input');
assert.equal(await page.evaluate(()=>window.testHost.overrides.size),1);
await page.locator('[data-nz-setting="enabled"]').uncheck();
assert.equal(await page.evaluate(()=>window.testHost.overrides.size),0);
assert.equal(await page.locator('body').getAttribute('data-nezuko-active'),null);
await page.locator('[data-nz-setting="enabled"]').check();
assert.equal(await page.evaluate(()=>window.testHost.overrides.size),1);
await page.evaluate(()=>window.testHost.disposers.forEach(f=>f()));
assert.equal(await page.locator('.nz-launcher,.nz-settings,.nz-petals').count(),0);
assert.equal(await page.evaluate(()=>window.testHost.overrides.size),0);
assert.equal(await page.evaluate(()=>window.testHost.listeners.size),0);
assert.equal(await page.locator('body').getAttribute('data-nezuko-active'),null);
assert.equal(errors.length,0,errors.join('\n'));
assert.ok(requests.every(u=>u.startsWith('file://'+root+'/')||u.startsWith('data:')||u.startsWith('blob:null/')),requests.join('\n'));
const report={date:'2026-09-12',checks:['self-contained preview loads','embedded artwork decodes and is applied to the scene','day/night switch','settings and preference persistence','focus mode','prompt entry and explicit demo response','user text escaping','command search and keyboard execution','conversation/code/guide screens','390px mobile layout without horizontal overflow','mobile navigation','reduced-motion support','native ModuleLoader bundle parses','native enable/disable/update lifecycle under host-contract fixture','native disposal removes owned effects','no external asset requests','no JavaScript page errors'],contrast:contrastReport,limits:['Native plugin checked against public DSH source and a host-contract fixture; not installed in the user’s DSH.','Preview illustrates the design; native DSH layout remains controlled by its own components.']};
fs.writeFileSync(path.join(root,'qa/validation.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
await browser.close();
